dist: trusty
sudo: false
group: stable
bundler_args: --without coverage development pcap
cache: bundler
addons:
  postgresql: '9.6'
  apt:
    packages:
      - libpcap-dev
      - graphviz
language: ruby
rvm:
  - '2.2'
  - '2.3.4'
  - '2.4.1'

env:
  - CMD='bundle exec rake rspec-rerun:spec SPEC_OPTS="--tag content"'
  - CMD='bundle exec rake rspec-rerun:spec SPEC_OPTS="--tag ~content"'

matrix:
  fast_finish: true
  include:
  - rvm: ruby-head
    env: CMD="docker-compose -f $TRAVIS_BUILD_DIR/docker-compose.yml build"
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version
  # Fail build if msftidy is not successful
  - ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
  - ls -la ./.git/hooks
  - ./.git/hooks/post-merge
  # Update the bundler
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  # fail build if db/schema.rb update is not committed
  - git diff --exit-code db/schema.rb
script:
  - echo "${CMD}"
  - bash -c "${CMD}"

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5

# Blacklist certain branches from triggering travis builds
branches:
  except:
    - gh-pages
    - metakitty

services:
  - docker
