version: '2'
services:
  ms:
    image: metasploit
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf
    links:
      - db
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:9-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
